#!/bin/sh

dpkg-scanpackages -m . /dev/null >Packages

bzip2 -fskz Packages

touch ./releasetmp

echo "Origin: Hacked Repo
Label: Hacked Repo
Suite: stable 
Version: 1.0
Codename: hack
Architectures: iphoneos-arm 
Components: main
Description: Hacked repository with leet hacker scripts"  > ./Release

MD5_PACKAGES="$(md5 ./Packages)"
MD5_PACKAGES_CONDENSED=${MD5_PACKAGES#'MD5 (./Packages) ='}
PACKAGES_SIZE="$(stat -f%z Packages)"

MD5_PACKAGESBZ="$(md5 ./Packages.bz2)"
MD5_PACKAGESBZ_CONDENSED=${MD5_PACKAGESBZ#'MD5 (./Packages.bz2) ='}
PACKAGESBZ_SIZE="$(stat -f%z Packages.bz2)"

echo "MD5Sum:
$MD5_PACKAGES_CONDENSED $PACKAGES_SIZE Packages
$MD5_PACKAGESBZ_CONDENSED $PACKAGESBZ_SIZE Packages.bz2" >> ./Release

read -p "Would create a new Release.gpg? [Y/N] " -n 1 -r
        echo    # (optional) move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]]; then
gpg -abs -o Release.gpg Release

fi






